<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>Спасибо за регистрацию</title>
    <style>
        h1 {
            color: cadetblue;
        }
        h2 {
            color: red;
        }
    </style>
</head>
<body>
<h1>Ссылка на регистрацию:</h1>
<img src="https://sf-tb-sg.ibytedtos.com/obj/eden-sg/uhtyvueh7nulogpoguhm/tiktok-icon2.png" alt="">
<h2><a href="http://localhost:1337/confirm/${confirm_code}">Пройдите по ссылке</a></h2>
</body>
</html>